# Sponsor button configuration - see
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: BrianGilbert
custom:
  - https://www.buymeacoffee.com/itsvrk
  - https://paypal.me/VRKforReal
